/* Topic lessons shown on each topic's "Learn" tab.
   Each topic is a list of sections: { title, text?, points?: [..], tip? }. */

const TOPIC_LESSONS = {
  // ---------------- Maths ----------------
  "y7-computation": [
    { title: "Place value",
      text: "Each digit's value depends on where it sits. In 4,372 the 4 is worth 4000, the 3 is worth 300, the 7 is worth 70 and the 2 is worth 2.",
      points: ["Expanded form breaks a number into place values: 4372 = 4000 + 300 + 70 + 2.", "Powers of 10 can be written with index notation: 1000 = 10³, so 5000 = 5 × 10³."] },
    { title: "Adding and subtracting",
      text: "Line numbers up by place value and work from the ones column to the left.",
      points: ["Adding: if a column adds to 10 or more, carry the ten into the next column.", "Subtracting: if the top digit is too small, borrow from the next column.", "Mental shortcut: 650 - 180 = 650 - 100 - 80 = 470."] },
    { title: "Multiplying and dividing",
      points: ["Split big multiplications into easier parts: 17 × 23 = 17 × 20 + 17 × 3 = 340 + 51 = 391.", "Division is the reverse of multiplication: 72 ÷ 9 = 8 because 9 × 8 = 72.", "Knowing your times tables up to 12 × 12 makes everything faster."] },
    { title: "Order of operations (BIDMAS)",
      text: "When a calculation has more than one operation, do them in this order:",
      points: ["B — Brackets first", "I — Indices (powers like 2³)", "D M — Division and Multiplication, left to right", "A S — Addition and Subtraction, left to right", "Example: 12 + 36 ÷ 4 = 12 + 9 = 21 (not 48 ÷ 4 = 12)."] },
    { title: "Rounding",
      text: "Look at the digit just to the right of the place you're rounding to. If it's 5 or more, round up; if it's 4 or less, round down.",
      points: ["4867 to the nearest hundred: the tens digit is 6, so round up to 4900."] },
  ],
  "y7-numberprops": [
    { title: "Factors and multiples",
      points: ["A factor divides a number exactly. Factors of 12: 1, 2, 3, 4, 6, 12.", "A multiple is in a number's times table. Multiples of 4: 4, 8, 12, 16…", "The HCF (highest common factor) is the biggest factor two numbers share. HCF of 18 and 24 is 6.", "The LCM (lowest common multiple) is the smallest multiple two numbers share. LCM of 4 and 6 is 12."] },
    { title: "Prime and composite numbers",
      text: "A prime number has exactly two factors: 1 and itself. A composite number has more than two.",
      points: ["The first primes are 2, 3, 5, 7, 11, 13, 17, 19, 23, 29.", "2 is the only even prime.", "1 is neither prime nor composite.", "Prime factorisation writes a number as primes multiplied together: 60 = 2 × 2 × 3 × 5."] },
    { title: "Squares, cubes and square roots",
      points: ["Squaring multiplies a number by itself: 7² = 7 × 7 = 49.", "Cubing uses it three times: 2³ = 2 × 2 × 2 = 8.", "A square root undoes squaring: √49 = 7 because 7² = 49."] },
    { title: "Number patterns",
      text: "Find the rule by looking at how each term changes.",
      points: ["Adding the same amount: 100, 91, 82, 73 → subtract 9 each time.", "Multiplying: 3, 6, 12, 24 → double each time.", "To jump ahead: the 10th term of 4, 7, 10… is 4 + 9 × 3 = 31."] },
  ],
  "y7-fdp": [
    { title: "What a fraction means",
      text: "A fraction shows parts of a whole. The denominator (bottom) is how many equal parts; the numerator (top) is how many you have. 3/8 means 3 out of 8 equal parts." },
    { title: "Equivalent and simplified fractions",
      points: ["Multiply or divide the top and bottom by the same number to get an equivalent fraction: 1/2 = 2/4 = 4/8.", "To simplify, divide both by their HCF: 24/36 ÷ 12 = 2/3.", "Mixed numbers ↔ improper fractions: 1 1/4 = 5/4."] },
    { title: "Adding, subtracting, multiplying and dividing",
      points: ["Add or subtract: make the denominators the same first. 1/2 + 1/4 = 2/4 + 1/4 = 3/4.", "Multiply: tops × tops, bottoms × bottoms. 2/3 × 3/5 = 6/15 = 2/5.", "Divide: flip the second fraction and multiply. 3/4 ÷ 1/2 = 3/4 × 2/1 = 3/2."] },
    { title: "Fractions, decimals and percentages",
      text: "They're three ways to write the same amount. Percent means 'out of 100'.",
      points: ["Fraction → decimal: divide top by bottom. 3/8 = 3 ÷ 8 = 0.375.", "Decimal → percentage: × 100. 0.375 = 37.5%.", "Useful ones to remember: 1/2 = 50%, 1/4 = 25%, 3/4 = 75%, 1/5 = 20%, 1/10 = 10%."] },
    { title: "Finding a percentage of an amount",
      points: ["10% = divide by 10. 10% of 90 = 9.", "Build others from 10%: 35% of 80 = 3 × 8 + 4 = 28.", "Or multiply by the decimal: 15% of 80 = 0.15 × 80 = 12."],
      tip: "A 15% increase on $80 means 80 + 12 = $92." },
  ],
  "y7-algebra": [
    { title: "Pronumerals",
      text: "A pronumeral is a letter that stands for a number. In 3x + 5, x is the pronumeral.",
      points: ["3x means 3 × x. We leave out the × sign.", "The coefficient is the number in front of the letter (3 in 3x).", "A constant is a term with no letter (5 in 3x + 5).", "Terms are separated by + and - signs: 3x + 5y - 7 has 3 terms."] },
    { title: "Substitution",
      text: "Replace the letter with its value, then follow the order of operations.",
      points: ["5c + 10 when c = 4 → 5 × 4 + 10 = 30.", "2p² when p = 3 → 2 × 3 × 3 = 18 (square first, then multiply)."] },
    { title: "Simplifying: collecting like terms",
      text: "Like terms have exactly the same letters. You can add or subtract them by combining coefficients.",
      points: ["4x + 3x - 2x = 5x", "5x + 3y - 2x + y = 3x + 4y (x terms and y terms kept separate)", "12m ÷ 4 = 3m and 2x × 4 = 8x"] },
    { title: "Expanding brackets",
      text: "Multiply the number outside by every term inside.",
      points: ["3(x + 4) = 3x + 12", "4(y - 2) = 4y - 8", "Then collect like terms: 3(x + 2) + 2x = 3x + 6 + 2x = 5x + 6."] },
  ],
  "y7-decimals": [
    { title: "Decimal place value",
      text: "Digits after the decimal point are tenths, hundredths, thousandths… In 4.375 the 3 is 3 tenths, the 7 is 7 hundredths and the 5 is 5 thousandths.",
      points: ["To compare decimals, compare digit by digit from the left: 0.7 > 0.65 because 7 tenths > 6 tenths."] },
    { title: "Adding and subtracting",
      text: "Always line up the decimal points. Fill empty places with zeros if it helps.",
      points: ["3.45 + 2.60 = 6.05", "10.00 - 3.45 = 6.55"] },
    { title: "Multiplying and dividing by 10, 100, 1000",
      points: ["× 10 moves digits one place left: 2.5 × 10 = 25.", "÷ 100 moves digits two places right: 3.6 ÷ 100 = 0.036."] },
    { title: "Multiplying decimals",
      text: "Multiply as if there were no decimal points, then count the total decimal places in the question and put that many in the answer.",
      points: ["0.6 × 0.4: 6 × 4 = 24, two decimal places → 0.24.", "2.4 × 1.5: 24 × 15 = 360, two decimal places → 3.60."] },
    { title: "Dividing by a decimal",
      text: "Multiply both numbers by 10 (or 100) until you're dividing by a whole number.",
      points: ["8.4 ÷ 0.2 = 84 ÷ 2 = 42", "1.44 ÷ 0.12 = 144 ÷ 12 = 12"] },
    { title: "Rounding",
      text: "Look at the next digit after the place you're keeping. 5 or more rounds up; 4 or less stays.",
      points: ["5.278 to 2 d.p. → the next digit is 8, so 5.28."] },
  ],
  "y7-negatives": [
    { title: "The number line",
      text: "Negative numbers are less than zero. On a number line they sit to the left of 0. The further left, the smaller: -9 < -3 < 0 < 4.",
      points: ["The opposite of 7 is -7 — the same distance from 0 on the other side."] },
    { title: "Adding and subtracting",
      points: ["Adding a positive: move right. -8 + 3 = -5.", "Subtracting a positive: move left. 7 - 12 = -5.", "Adding a negative is the same as subtracting: 10 + (-14) = 10 - 14 = -4.", "Subtracting a negative is the same as adding: 8 - (-6) = 8 + 6 = 14."],
      tip: "Two signs side by side: same signs (+ + or - -) make +, different signs (+ - or - +) make -." },
    { title: "Multiplying and dividing",
      points: ["Positive × positive = positive", "Negative × negative = positive: -7 × -3 = 21", "Positive × negative = negative: -4 × 6 = -24", "The same rules work for division: -18 ÷ -3 = 6, -20 ÷ 4 = -5"] },
    { title: "The Cartesian plane",
      text: "Points are written (x, y). x tells you left/right, y tells you up/down. The four quadrants are numbered anticlockwise from the top right:",
      points: ["Quadrant 1: (+, +) top right", "Quadrant 2: (-, +) top left", "Quadrant 3: (-, -) bottom left", "Quadrant 4: (+, -) bottom right"] },
  ],
  "y7-geometry": [
    { title: "Types of angles",
      points: ["Acute: less than 90°", "Right: exactly 90°", "Obtuse: between 90° and 180°", "Straight: exactly 180°", "Reflex: between 180° and 360°", "Revolution (full turn): 360°"] },
    { title: "Angle rules",
      points: ["Complementary angles add to 90°.", "Supplementary angles (on a straight line) add to 180°.", "Angles around a point add to 360°.", "Vertically opposite angles are equal."] },
    { title: "Parallel lines",
      text: "When a line (a transversal) crosses two parallel lines:",
      points: ["Corresponding angles are equal (F shape).", "Alternate angles are equal (Z shape).", "Co-interior angles add to 180° (C shape)."] },
    { title: "Triangles and quadrilaterals",
      points: ["Angles in a triangle add to 180°.", "Equilateral: 3 equal sides and angles (60° each). Isosceles: 2 equal sides and 2 equal base angles. Scalene: all different.", "Angles in a quadrilateral add to 360°.", "An exterior angle of a triangle equals the sum of the two opposite interior angles."] },
    { title: "Polygons",
      points: ["Pentagon 5 sides, hexagon 6, octagon 8.", "Angle sum of any polygon = (n - 2) × 180°, where n is the number of sides.", "In a regular polygon all angles are equal, so divide the angle sum by n: a regular hexagon has 720° ÷ 6 = 120° angles."] },
  ],
  "y7-statsprob": [
    { title: "Mean, median, mode and range",
      points: ["Mean (average): add all values, then divide by how many there are.", "Median: put the values in order and take the middle one. With an even count, average the two middle values.", "Mode: the value that appears most often.", "Range: highest value - lowest value. It shows how spread out the data is."] },
    { title: "Worked example",
      text: "Data: 8, 3, 12, 3, 20, 15",
      points: ["In order: 3, 3, 8, 12, 15, 20", "Mean = 61 ÷ 6 ≈ 10.2", "Median = (8 + 12) ÷ 2 = 10", "Mode = 3", "Range = 20 - 3 = 17"] },
    { title: "Probability",
      text: "Probability measures how likely something is, from 0 (impossible) to 1 (certain). It can be written as a fraction, decimal or percentage.",
      points: ["Probability = favourable outcomes ÷ total outcomes.", "Rolling an even number on a die: 3 out of 6 = 1/2 = 50%.", "P(not A) = 1 - P(A). If P(red) = 50%, P(not red) = 50%."] },
    { title: "Experimental probability",
      text: "When you actually do an experiment, experimental probability = times it happened ÷ total trials. A coin landing tails 27 times out of 60 gives 27/60 = 45%." },
  ],
  "y7-equations": [
    { title: "What is an equation?",
      text: "An equation says two things are equal, like a balanced scale. Solving it means finding the value of the pronumeral that makes both sides equal." },
    { title: "Inverse operations",
      text: "Undo what's been done to x by doing the opposite to both sides.",
      points: ["+ is undone by -, and × is undone by ÷.", "x + 9 = 15 → subtract 9 from both sides → x = 6.", "x / 4 = 7 → multiply both sides by 4 → x = 28."] },
    { title: "Two-step equations",
      text: "Undo the adding/subtracting first, then the multiplying/dividing.",
      points: ["3x - 4 = 20", "Add 4 to both sides: 3x = 24", "Divide both sides by 3: x = 8"],
      tip: "Check your answer by substituting it back: 3 × 8 - 4 = 20 ✓" },
    { title: "Brackets and pronumerals on both sides",
      points: ["Expand brackets first: 2(x - 5) = 18 → 2x - 10 = 18 → 2x = 28 → x = 14.", "Move pronumerals to one side: 7x + 3 = 4x + 18 → subtract 4x → 3x + 3 = 18 → x = 5."] },
    { title: "Formulas and word problems",
      text: "Turn the words into an equation, then solve. 'Twice a number plus 9 equals 23' → 2n + 9 = 23 → n = 7." },
  ],
  "y7-measurement": [
    { title: "Converting units",
      points: ["Length: 10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km", "Mass: 1000 g = 1 kg", "Capacity: 1000 mL = 1 L, and 1 mL = 1 cm³", "Going to a smaller unit, multiply. Going to a larger unit, divide."] },
    { title: "Perimeter",
      text: "Perimeter is the distance around the outside of a shape. Add up all the side lengths.",
      points: ["Rectangle: P = 2 × (length + width)", "Circle (circumference): C = π × diameter = 2 × π × radius"] },
    { title: "Area",
      text: "Area is the space inside a 2D shape, measured in square units (cm², m²).",
      points: ["Rectangle: A = length × width", "Triangle: A = ½ × base × height", "Parallelogram: A = base × height", "Trapezium: A = ½ × (a + b) × height", "Circle: A = π × radius²", "Composite shapes: split into simple shapes and add the areas."] },
    { title: "Volume",
      text: "Volume is the space inside a 3D object, measured in cubic units (cm³, m³).",
      points: ["Rectangular prism: V = length × width × height", "Any prism: V = area of the cross-section × length"] },
  ],

  // ---------------- English ----------------
  "eng-punctuation": [
    { title: "Ending a sentence",
      points: ["Full stop (.) ends a statement: The bus is late.", "Question mark (?) ends a question: What time is it?", "Exclamation mark (!) shows strong feeling: Watch out!"] },
    { title: "Capital letters",
      points: ["At the start of every sentence.", "For names of people, places, days and months: Mia, Melbourne, Monday, May.", "For the word I."] },
    { title: "Commas",
      points: ["Separate items in a list: apples, bananas and pears.", "After an introductory phrase: After lunch, we went outside.", "Around extra information: My dog, who loves the beach, is asleep.", "Before a closing speech mark in dialogue: 'I'm hungry,' said Sam."] },
    { title: "Apostrophes",
      points: ["Contractions — show missing letters: it is → it's, do not → don't.", "Possession — show ownership: the dog's bone (one dog), the dogs' bone (more than one dog).", "its (belonging to it) has no apostrophe; it's always means 'it is' or 'it has'."] },
    { title: "Colons and semicolons",
      points: ["A semicolon (;) joins two closely related complete sentences: I was tired; I went to bed.", "A colon (:) introduces a list or explanation: You need three things: a pen, paper and a ruler."] },
  ],
  "eng-spelling": [
    { title: "Plurals",
      points: ["Most words add -s: cat → cats.", "Words ending in s, x, ch, sh add -es: box → boxes, church → churches.", "Consonant + y → -ies: baby → babies.", "Some are irregular: child → children, mouse → mice."] },
    { title: "Useful rules",
      points: ["i before e except after c: believe, receive (with exceptions like weird).", "Adding a suffix to a word ending in e: drop the e before a vowel — make → making.", "Short vowel + one consonant: double it before -ing/-ed — run → running, stop → stopped."] },
    { title: "Homophones",
      text: "Homophones sound the same but have different spellings and meanings.",
      points: ["there (a place), their (belongs to them), they're (they are)", "your (belongs to you), you're (you are)", "to (towards), too (also / too much), two (2)", "affect (a verb — to influence), effect (a noun — a result)", "who's (who is), whose (belonging to whom)"] },
    { title: "Tricky words to learn",
      text: "Some words just have to be memorised: definitely, separate, necessary, accommodate, receive, friend, because, beautiful.",
      tip: "Look for memory tricks: there's 'a rat' in sep-a-rat-e, and necessary has one collar (c) and two sleeves (ss)." },
  ],
  "eng-reading": [
    { title: "Read it twice",
      text: "Read the passage once to get the general idea, then read the question and go back to find the evidence." },
    { title: "Three kinds of questions",
      points: ["Literal (right there): the answer is stated in the text. 'What did Tom feed his dog?'", "Inference (reading between the lines): use clues to work out what isn't said directly. If a character's hands tremble, they're probably nervous.", "Main idea: what is the passage mostly about? Look at the first and last sentences."] },
    { title: "Using evidence",
      text: "Good answers point to words in the text. Ask yourself: 'Which words tell me this?'",
      tip: "Watch for signal words — 'because' shows a reason, 'although' and 'despite' show a contrast, 'so' shows a result." },
    { title: "Working out new words",
      text: "If you meet an unfamiliar word, use the rest of the sentence as a clue to its meaning." },
  ],
  "eng-grammar": [
    { title: "Parts of speech",
      points: ["Noun — a person, place, thing or idea: dog, Sydney, happiness", "Verb — an action or state: run, is, think", "Adjective — describes a noun: tall, red, fluffy", "Adverb — describes a verb, often ending in -ly: quickly, loudly", "Pronoun — replaces a noun: he, she, it, they, who", "Conjunction — joins words or clauses: and, but, so, because, although", "Preposition — shows position or relationship: on, under, between, after"] },
    { title: "Verb tenses",
      points: ["Past: I walked. Present: I walk. Future: I will walk.", "Irregular verbs don't just add -ed: bring → brought, write → wrote → written, go → went."] },
    { title: "Subject–verb agreement",
      text: "A singular subject needs a singular verb, and a plural subject needs a plural verb.",
      points: ["The cat is… / The cats are…", "Words like everyone, each, neither and nobody are singular: Everyone is here.", "Find the real subject: The list of names is on the wall (the list is)."] },
    { title: "Sentence types",
      points: ["Simple: one main clause — I ran home.", "Compound: two main clauses joined by and, but, or, so — I ran home, but I was late.", "Complex: a main clause plus a dependent clause — Although I ran, I was late.", "A fragment is incomplete: Because it was raining. (What happened?)"] },
    { title: "Active and passive voice",
      points: ["Active: the doer comes first — Tom ate the cake.", "Passive: the thing acted on comes first — The cake was eaten by Tom.", "Active voice is usually clearer and stronger."] },
  ],
  "eng-vocab": [
    { title: "Synonyms and antonyms",
      points: ["Synonyms mean the same or nearly the same: big, large, enormous, gigantic.", "Antonyms mean the opposite: hot / cold, generous / selfish, include / exclude."],
      tip: "Swapping a plain word for a precise synonym makes writing more vivid: 'walked' → 'strolled', 'trudged' or 'marched'." },
    { title: "Prefixes",
      text: "A prefix goes at the start of a word and changes its meaning.",
      points: ["un-, im-, in-, dis- = not: unhappy, impossible, invisible, dishonest", "pre- = before: preview", "re- = again: rewrite", "mis- = wrongly: misunderstand", "sub- = under: submarine"] },
    { title: "Suffixes",
      text: "A suffix goes at the end of a word and often changes its word class.",
      points: ["-ness makes a noun: kind → kindness", "-less = without: fearless", "-ful = full of: hopeful", "-able = can be: reliable"] },
    { title: "Word roots",
      points: ["bio = life (biology)", "chron = time (chronological)", "geo = earth (geography)", "tele = far (telephone)", "graph = write (autograph)"] },
    { title: "Context clues",
      text: "When you don't know a word, use the rest of the sentence. 'The desert was arid; no rain had fallen for months' — the clue about no rain tells you arid means very dry." },
  ],
  "eng-figurative": [
    { title: "Comparisons",
      points: ["Simile: compares using 'like' or 'as' — as fast as a cheetah, fought like a lion.", "Metaphor: says something IS something else — The classroom was a zoo. Time is a thief."],
      tip: "Quick test: if you can spot 'like' or 'as' doing the comparing, it's a simile." },
    { title: "Personification",
      text: "Giving human actions or feelings to something that isn't human: The wind whispered. The old car coughed up the hill." },
    { title: "Sound devices",
      points: ["Alliteration: the same starting sound repeated — silly snakes slither slowly.", "Onomatopoeia: words that sound like the noise — buzz, crash, sizzle, hiss."] },
    { title: "Exaggeration and contrast",
      points: ["Hyperbole: huge exaggeration for effect — I've told you a million times!", "Oxymoron: two opposite words together — jumbo shrimp, deafening silence."] },
    { title: "Idioms",
      text: "An idiom is a saying whose meaning is different from its actual words.",
      points: ["It's raining cats and dogs — raining heavily", "A piece of cake — very easy", "Spill the beans — tell a secret", "Break a leg — good luck"] },
  ],

  // ---------------- Writing ----------------
  "eng-creative": [
    { title: "Plan before you write",
      text: "Spend a couple of minutes deciding on your character, setting and the problem they face. A short story needs one clear problem, not five." },
    { title: "Story structure",
      points: ["Orientation: introduce who, where and when — and hook the reader.", "Complication: something goes wrong or changes.", "Rising action: the problem gets bigger or harder.", "Climax: the most tense moment.", "Resolution: how it ends — it doesn't have to be happy, but it should feel finished."] },
    { title: "Make it vivid",
      points: ["Show, don't tell: instead of 'She was scared', write 'Her hands shook as she reached for the handle.'", "Use the senses — what can the character hear, smell and feel?", "Choose precise verbs and adjectives, and add some figurative language.", "Vary your sentences: mix short, punchy ones with longer ones."] },
    { title: "Check before you hand in",
      text: "Re-read for capital letters, full stops, speech marks and spelling. Then ask for AI feedback and fix one or two things it suggests." },
  ],
  "eng-essay": [
    { title: "Decide your position",
      text: "Read the prompt carefully and choose your side (or, for a discussion essay, the two sides you'll compare). Your main argument is your thesis." },
    { title: "Essay structure",
      points: ["Introduction: hook the reader, give background, and state your thesis clearly.", "Body paragraphs (usually 3): one main point each.", "Conclusion: restate your thesis in new words, sum up your points, end with a strong final thought. No new arguments."] },
    { title: "Build each body paragraph (TEEL)",
      points: ["T — Topic sentence: state the paragraph's main point.", "E — Explain: say why it matters.", "E — Evidence: give an example, fact or statistic.", "L — Link: connect back to your thesis."] },
    { title: "Persuasive techniques",
      points: ["Linking words: firstly, furthermore, however, therefore, in conclusion.", "Rhetorical questions: 'Wouldn't you want to feel safe at school?'", "Inclusive language: 'we', 'us', 'our community'.", "Address the other side, then explain why your view is stronger."] },
  ],
};
